import type { Pack } from '../types';

export function zhSeedPacks(): Pack[] {
  return [
    {
      id: 'seed-zh-qingtian',
      title: '周杰伦 — 晴天',
      subtitle: 'Солнечный день · 晴天',
      emoji: '☀️',
      colorHex: '#FFB300',
      difficulty: 'Начальный',
      sourceId: null,
      language: 'zh',
      wordDefs: [
        { korean: '晴天', translation: 'солнечный день', pinyin: 'qíng tiān' },
        { korean: '故事', translation: 'история', pinyin: 'gù shi' },
        { korean: '开始', translation: 'начинать', pinyin: 'kāi shǐ' },
        { korean: '下雨', translation: 'идёт дождь', pinyin: 'xià yǔ' },
        { korean: '微笑', translation: 'улыбка', pinyin: 'wēi xiào' },
        { korean: '喜欢', translation: 'нравиться, любить', pinyin: 'xǐ huan' },
        { korean: '从前', translation: 'раньше, когда-то', pinyin: 'cóng qián' },
      ],
      createdAt: 101,
    },
    {
      id: 'seed-zh-daoxiang',
      title: '周杰伦 — 稻香',
      subtitle: 'Аромат риса · 稻香',
      emoji: '🌾',
      colorHex: '#8BC34A',
      difficulty: 'Начальный',
      sourceId: null,
      language: 'zh',
      wordDefs: [
        { korean: '家乡', translation: 'родина, родной край', pinyin: 'jiā xiāng' },
        { korean: '梦想', translation: 'мечта', pinyin: 'mèng xiǎng' },
        { korean: '努力', translation: 'стараться, усердие', pinyin: 'nǔ lì' },
        { korean: '快乐', translation: 'счастливый, радость', pinyin: 'kuài lè' },
        { korean: '童年', translation: 'детство', pinyin: 'tóng nián' },
        { korean: '河流', translation: 'река', pinyin: 'hé liú' },
        { korean: '阳光', translation: 'солнечный свет', pinyin: 'yáng guāng' },
      ],
      createdAt: 102,
    },
    {
      id: 'seed-zh-chuanqi',
      title: '王菲 — 传奇',
      subtitle: 'Легенда · 传奇',
      emoji: '✨',
      colorHex: '#AB47BC',
      difficulty: 'Средний',
      sourceId: null,
      language: 'zh',
      wordDefs: [
        { korean: '传奇', translation: 'легенда', pinyin: 'chuán qí' },
        { korean: '眼睛', translation: 'глаза', pinyin: 'yǎn jing' },
        { korean: '月亮', translation: 'луна', pinyin: 'yuè liang' },
        { korean: '天空', translation: 'небо', pinyin: 'tiān kōng' },
        { korean: '相信', translation: 'верить', pinyin: 'xiāng xìn' },
        { korean: '永远', translation: 'навсегда', pinyin: 'yǒng yuǎn' },
      ],
      createdAt: 103,
    },
    {
      id: 'seed-zh-basics',
      title: 'C-drama — базовая лексика',
      subtitle: 'Повседневные фразы',
      emoji: '🎬',
      colorHex: '#26A69A',
      difficulty: 'Начальный',
      sourceId: null,
      language: 'zh',
      wordDefs: [
        { korean: '你好', translation: 'привет', pinyin: 'nǐ hǎo' },
        { korean: '谢谢', translation: 'спасибо', pinyin: 'xiè xie' },
        { korean: '对不起', translation: 'извините', pinyin: 'duì bu qǐ' },
        { korean: '没关系', translation: 'ничего страшного', pinyin: 'méi guān xi' },
        { korean: '喜欢', translation: 'нравиться', pinyin: 'xǐ huan' },
        { korean: '朋友', translation: 'друг', pinyin: 'péng you' },
        { korean: '今天', translation: 'сегодня', pinyin: 'jīn tiān' },
        { korean: '明天', translation: 'завтра', pinyin: 'míng tiān' },
      ],
      createdAt: 104,
    },
  ];
}
