import type { Pack } from '../types';
import { extendedSeedPacks } from './packs-extended';
import { stagedSeedPacks } from './packs-staged';
import { zhSeedPacks } from './packs-zh';

export function bootstrapPacks(): Pack[] {
  return allSeedPacks().filter((pack) => !pack.staged);
}

export function allSeedPacks(): Pack[] {
  return [
    {
      id: 'seed-bts-springday',
      title: 'BTS — Spring Day',
      subtitle: 'Мы встретимся снова · 다시 만날 거야',
      emoji: '🌸',
      colorHex: '#FF8A65',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '봄', translation: 'весна' },
        { korean: '하루', translation: 'одни сутки, день' },
        { korean: '여행', translation: 'путешествие' },
        { korean: '기억', translation: 'воспоминание, память' },
        { korean: '지나가다', translation: 'проходить, проходить мимо' },
        { korean: '기다리다', translation: 'ждать' },
        { korean: '사랑', translation: 'любовь' },
        { korean: '겨울', translation: 'зима' },
        { korean: '눈', translation: 'снег' },
        { korean: '친구', translation: 'друг' },
        { korean: '시간', translation: 'время' },
        { korean: '그립다', translation: 'скучать, томиться' },
        { korean: '꽃', translation: 'цветок' },
        { korean: '밤', translation: 'ночь' },
        { korean: '별', translation: 'звезда' },
        { korean: '길', translation: 'дорога, путь' },
        { korean: '약속', translation: 'обещание, встреча' },
        { korean: '다시', translation: 'снова' },
        { korean: '만나다', translation: 'встречать(ся)' },
        { korean: '보고 싶다', translation: 'скучать, хотеть увидеть' },
        { korean: '함께', translation: 'вместе' },
        { korean: '마음', translation: 'сердце, душа' },
        { korean: '눈물', translation: 'слёзы' },
        { korean: '추억', translation: 'воспоминание' },
        { korean: '멀다', translation: 'быть далеко' },
        { korean: '가다', translation: 'идти, ехать' },
        { korean: '오다', translation: 'приходить' },
        { korean: '영원', translation: 'вечность' },
        { korean: '따뜻하다', translation: 'быть тёплым' },
        { korean: '바람', translation: 'ветер' },
      ],
      createdAt: 1,
    },
    {
      id: 'seed-bts-butter',
      title: 'BTS — Butter',
      subtitle: 'Мягко, как масло · 버터처럼',
      emoji: '🧈',
      colorHex: '#FFD54F',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '춤', translation: 'танец' },
        { korean: '노래', translation: 'песня' },
        { korean: '춤추다', translation: 'танцевать', exampleSentence: '춤을 춰요', exampleTranslation: 'Танцую' },
        { korean: '좋다', translation: 'быть хорошим, нравиться' },
        { korean: '자신감', translation: 'уверенность' },
        { korean: '말', translation: 'слово, конь (разный ханжа)' },
        { korean: '서로', translation: 'друг друга, взаимно' },
        { korean: '빛', translation: 'свет' },
        { korean: '부드럽다', translation: 'быть мягким, плавным' },
        { korean: '밤', translation: 'ночь' },
        { korean: '달', translation: 'луна' },
        { korean: '멋있다', translation: 'быть крутым, стильным' },
        { korean: '매끄럽다', translation: 'быть гладким' },
        { korean: '화려하다', translation: 'быть ярким, эффектным' },
        { korean: '무대', translation: 'сцена' },
        { korean: '팬', translation: 'фанат' },
        { korean: '눈빛', translation: 'взгляд' },
        { korean: '분위기', translation: 'атмосфера' },
        { korean: '신나다', translation: 'быть весёлым, зажигательным' },
        { korean: '멜로디', translation: 'мелодия' },
        { korean: '리듬', translation: 'ритм' },
        { korean: '놀다', translation: 'играть, тусоваться' },
        { korean: '반짝이다', translation: 'блестеть, мерцать' },
        { korean: '매력', translation: 'очарование' },
        { korean: '스타일', translation: 'стиль' },
        { korean: '기분', translation: 'настроение' },
        { korean: '웃음', translation: 'смех' },
        { korean: '특별하다', translation: 'быть особенным' },
        { korean: '설레다', translation: 'волноваться, трепетать' },
        { korean: '하늘', translation: 'небо' },
        { korean: '별', translation: 'звезда' },
      ],
      createdAt: 2,
    },
    {
      id: 'seed-bts-dynamite',
      title: 'BTS — Dynamite',
      subtitle: 'Вспышка энергии · 다이너마이트',
      emoji: '🕺',
      colorHex: '#E040FB',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '자유', translation: 'свобода' },
        { korean: '기분', translation: 'настроение, самочувствие' },
        { korean: '비트', translation: 'бит (ритм)' },
        { korean: '앵콜', translation: 'бис (encore)' },
        { korean: '빛나다', translation: 'сиять, сверкать' },
        { korean: 'halo', translation: 'ореол' },
        { korean: 'halo가 빛나요', translation: 'Ореол сияет' },
        { korean: '터지다', translation: 'взрываться, вспыхивать' },
        { korean: '밝다', translation: 'быть ярким, светлым' },
        { korean: '즐기다', translation: 'наслаждаться' },
        { korean: '파티', translation: 'вечеринка' },
        { korean: '밤하늘', translation: 'ночное небо' },
        { korean: '반짝이다', translation: 'мерцать, блестеть' },
        { korean: '축하', translation: 'поздравление' },
        { korean: '에너지', translation: 'энергия' },
        { korean: '웃음', translation: 'смех' },
        { korean: '행복', translation: 'счастье' },
        { korean: '흥분', translation: 'волнение, азарт' },
        { korean: '특별하다', translation: 'быть особенным' },
        { korean: '불꽃', translation: 'искра, фейерверк' },
        { korean: '타오르다', translation: 'пылать, разгораться' },
        { korean: '소리', translation: 'звук' },
        { korean: '춤', translation: 'танец' },
        { korean: '노래', translation: 'песня' },
        { korean: '신나다', translation: 'быть зажигательным' },
        { korean: '밤', translation: 'ночь' },
        { korean: '별', translation: 'звезда' },
        { korean: '함께', translation: 'вместе' },
        { korean: '기억', translation: 'память, воспоминание' },
        { korean: '설레다', translation: 'трепетать, волноваться' },
        { korean: '온통', translation: 'повсюду, целиком' },
      ],
      createdAt: 3,
    },
    {
      id: 'seed-skz-maniac',
      title: 'Stray Kids — MANIAC',
      subtitle: 'Не будь обычным · 일반적이지 마',
      emoji: '🪲',
      colorHex: '#7C4DFF',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '이상', translation: 'ненормальный, странный' },
        { korean: '다르다', translation: 'быть другим, отличаться' },
        { korean: '미치다', translation: 'сойти с ума, безумный' },
        { korean: '자기', translation: 'себя, ты (ласково)' },
        { korean: '느끼다', translation: 'ощущать, чувствовать' },
        { korean: 'rules', translation: 'правила' },
        { korean: 'camouflage', translation: 'маскировка' },
        { korean: '정상', translation: 'норма, нормальный' },
        { korean: '비정상', translation: 'ненормальность' },
        { korean: '숨다', translation: 'прятаться' },
        { korean: '틀리다', translation: 'быть неправильным' },
        { korean: '특이하다', translation: 'быть необычным' },
        { korean: '반항', translation: 'протест, бунт' },
        { korean: '벗어나다', translation: 'вырываться, освобождаться' },
        { korean: '가면', translation: 'маска' },
        { korean: '거짓', translation: 'ложь' },
        { korean: '진짜', translation: 'настоящий' },
        { korean: '솔직하다', translation: 'быть честным' },
        { korean: '감추다', translation: 'прятать, скрывать' },
        { korean: '드러내다', translation: 'раскрывать, показывать' },
        { korean: '긴장', translation: 'напряжение' },
        { korean: '도전', translation: 'вызов' },
        { korean: '한계', translation: 'предел' },
        { korean: '돌아버리다', translation: 'сойти с ума' },
        { korean: '스트레스', translation: 'стресс' },
        { korean: '패턴', translation: 'шаблон, паттерн' },
        { korean: '무대', translation: 'сцена' },
        { korean: '성격', translation: 'характер' },
        { korean: '자유', translation: 'свобода' },
        { korean: '세상', translation: 'мир, общество' },
        { korean: '눈치', translation: 'сообразительность, tact' },
      ],
      createdAt: 4,
    },
    {
      id: 'seed-skz-sclass',
      title: 'Stray Kids — S-Class',
      subtitle: 'Сияй по-своему · S클래스',
      emoji: '💎',
      colorHex: '#00BCD4',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '별', translation: 'звезда' },
        { korean: '빛나다', translation: 'сиять, сверкать' },
        { korean: '매력', translation: 'очарование, привлекательность' },
        { korean: '개성', translation: 'индивидуальность' },
        { korean: '자신감', translation: 'уверенность' },
        { korean: 'Style', translation: 'стиль' },
        { korean: 'S클래스', translation: 'S-класс (уровень)' },
        { korean: '등급', translation: 'уровень, класс' },
        { korean: '최고', translation: 'лучший, высший' },
        { korean: '존재감', translation: 'charisma, присутствие' },
        { korean: '무대', translation: 'сцена' },
        { korean: '주목', translation: 'внимание' },
        { korean: '눈부시다', translation: 'ослепительный, яркий' },
        { korean: '화려하다', translation: 'блестящий, эффектный' },
        { korean: '독특하다', translation: 'уникальный' },
        { korean: '자랑', translation: 'гордость' },
        { korean: '승리', translation: 'победа' },
        { korean: '완벽', translation: 'совершенство' },
        { korean: '뛰어나다', translation: 'выдающийся' },
        { korean: '꿈', translation: 'мечта' },
        { korean: '멋지다', translation: 'классный, крутой' },
        { korean: '우리', translation: 'мы' },
        { korean: '함께', translation: 'вместе' },
        { korean: '세계', translation: 'мир' },
        { korean: '무대력', translation: 'сценическое мастерство' },
        { korean: '리더', translation: 'лидер' },
        { korean: '팀', translation: 'команда' },
        { korean: '열정', translation: 'страсть' },
        { korean: '도전', translation: 'вызов' },
        { korean: '성공', translation: 'успех' },
        { korean: '반짝이다', translation: 'мерцать, блестеть' },
      ],
      createdAt: 5,
    },
    ...stagedSeedPacks(),
    ...extendedSeedPacks(),
    ...zhSeedPacks(),
  ];
}