import type { Pack } from '../types';

/** Song missions unlocked via «Обновить подборку» / remote catalog sync. */
export function stagedSeedPacks(): Pack[] {
  return [
    {
      id: 'seed-bts-boywithluv',
      title: 'BTS — Boy With Luv',
      subtitle: 'Лёгкость и улыбка · 작은 것에 감사',
      emoji: '💜',
      colorHex: '#F48FB1',
      difficulty: 'Начальный',
      sourceId: null,
      staged: true,
      wordDefs: [
        { korean: '사랑', translation: 'любовь' },
        { korean: '미소', translation: 'улыбка' },
        { korean: '웃다', translation: 'смеяться, улыбаться' },
        { korean: '행복', translation: 'счастье' },
        { korean: '하늘', translation: 'небо' },
        { korean: '별', translation: 'звезда' },
        { korean: '꿈', translation: 'мечта' },
        { korean: '마음', translation: 'сердце, душа' },
        { korean: '함께', translation: 'вместе' },
        { korean: '기억', translation: 'воспоминание' },
        { korean: '설레다', translation: 'волноваться, трепетать' },
        { korean: '고마워', translation: 'спасибо (неформально)' },
        { korean: '예쁘다', translation: 'быть красивым' },
        { korean: '빛나다', translation: 'сиять' },
        { korean: '노래', translation: 'песня' },
        { korean: '춤', translation: 'танец' },
        { korean: '세상', translation: 'мир, свет' },
        { korean: '오늘', translation: 'сегодня' },
        { korean: '매일', translation: 'каждый день' },
        { korean: '좋아하다', translation: 'нравиться, любить' },
      ],
      createdAt: 6,
    },
    {
      id: 'seed-bts-ptd',
      title: 'BTS — Permission to Dance',
      subtitle: 'Танцуй свободно · 춤추자',
      emoji: '🕺',
      colorHex: '#42A5F5',
      difficulty: 'Начальный',
      sourceId: null,
      staged: true,
      wordDefs: [
        { korean: '춤', translation: 'танец' },
        { korean: '춤추다', translation: 'танцевать' },
        { korean: '음악', translation: 'музыка' },
        { korean: '자유', translation: 'свобода' },
        { korean: '밤', translation: 'ночь' },
        { korean: '별', translation: 'звезда' },
        { korean: '함께', translation: 'вместе' },
        { korean: '웃음', translation: 'смех' },
        { korean: '기분', translation: 'настроение' },
        { korean: '신나다', translation: 'быть весёлым' },
        { korean: '파티', translation: 'вечеринка' },
        { korean: '세상', translation: 'мир' },
        { korean: '희망', translation: 'надежда' },
        { korean: '빛', translation: 'свет' },
        { korean: '손', translation: 'рука' },
        { korean: '들다', translation: 'поднимать' },
        { korean: '모두', translation: 'все' },
        { korean: '즐기다', translation: 'наслаждаться' },
        { korean: '행복', translation: 'счастье' },
        { korean: '오늘', translation: 'сегодня' },
      ],
      createdAt: 7,
    },
    {
      id: 'seed-skz-godsmenu',
      title: "Stray Kids — God's Menu",
      subtitle: 'Острый рецепт · 신메뉴',
      emoji: '🌶️',
      colorHex: '#EF5350',
      difficulty: 'Начальный',
      sourceId: null,
      staged: true,
      wordDefs: [
        { korean: '메뉴', translation: 'меню' },
        { korean: '맛', translation: 'вкус' },
        { korean: '요리', translation: 'блюдо, готовка' },
        { korean: '불', translation: 'огонь' },
        { korean: '매운맛', translation: 'острый вкус' },
        { korean: '재료', translation: 'ингредиент' },
        { korean: '레시피', translation: 'рецепт' },
        { korean: '섞다', translation: 'смешивать' },
        { korean: '특별하다', translation: 'быть особенным' },
        { korean: '완벽', translation: 'совершенство' },
        { korean: '도전', translation: 'вызов' },
        { korean: '열정', translation: 'страсть' },
        { korean: '무대', translation: 'сцена' },
        { korean: '비트', translation: 'бит' },
        { korean: '강하다', translation: 'быть сильным' },
        { korean: '중독', translation: 'зависимость, «подсаживание»' },
        { korean: '반하다', translation: 'влюбиться, «подсесть»' },
        { korean: '신메뉴', translation: 'новое меню' },
        { korean: '맛있다', translation: 'быть вкусным' },
        { korean: '끝내주다', translation: 'быть потрясающим' },
      ],
      createdAt: 8,
    },
  ];
}
