import type { Pack } from '../types';
import { zhSeedPacks } from './packs-zh';

export function allSeedPacks(): Pack[] {
  return [
    {
      id: 'seed-bts-springday',
      title: 'BTS — Spring Day',
      subtitle: 'Мы встретимся снова · 다시 만날 거야',
      emoji: '🌸',
      colorHex: '#FF8A65',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '봄', translation: 'весна' },
        { korean: '하루', translation: 'одни сутки, день' },
        { korean: '여행', translation: 'путешествие' },
        { korean: '기억', translation: 'воспоминание, память' },
        { korean: '지나가다', translation: 'проходить, проходить мимо' },
        { korean: '기다리다', translation: 'ждать' },
        { korean: '사랑', translation: 'любовь' },
      ],
      createdAt: 1,
    },
    {
      id: 'seed-bts-butter',
      title: 'BTS — Butter',
      subtitle: 'Мягко, как масло · 버터처럼',
      emoji: '🧈',
      colorHex: '#FFD54F',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '춤', translation: 'танец' },
        { korean: '노래', translation: 'песня' },
        { korean: '춤추다', translation: 'танцевать', exampleSentence: '춤을 춰요', exampleTranslation: 'Танцую' },
        { korean: '좋다', translation: 'быть хорошим, нравиться' },
        { korean: '자신감', translation: 'уверенность' },
        { korean: '말', translation: 'слово, конь (разный ханжа)' },
        { korean: '서로', translation: 'друг друга, взаимно' },
        { korean: '빛', translation: 'свет' },
      ],
      createdAt: 2,
    },
    {
      id: 'seed-bts-dynamite',
      title: 'BTS — Dynamite',
      subtitle: 'Вспышка энергии · 다이너마이트',
      emoji: '🕺',
      colorHex: '#E040FB',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '자유', translation: 'свобода' },
        { korean: '기분', translation: 'настроение, самочувствие' },
        { korean: '비트', translation: 'бит (ритм)' },
        { korean: '앵콜', translation: 'бис (encore)' },
        { korean: '빛나다', translation: 'сиять, сверкать' },
        { korean: 'halo', translation: 'ореол' },
        { korean: 'halo가 빛나요', translation: 'Ореол сияет' },
      ],
      createdAt: 3,
    },
    {
      id: 'seed-skz-maniac',
      title: 'Stray Kids — MANIAC',
      subtitle: 'Не будь обычным · 일반적이지 마',
      emoji: '🪲',
      colorHex: '#7C4DFF',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '이상', translation: 'ненормальный, странный' },
        { korean: '다르다', translation: 'быть другим, отличаться' },
        { korean: '미치다', translation: 'сойти с ума, безумный' },
        { korean: '자기', translation: 'себя, ты (ласково)' },
        { korean: '느끼다', translation: 'ощущать, чувствовать' },
        { korean: 'rules', translation: 'правила' },
        { korean: 'camouflage', translation: 'маскировка' },
      ],
      createdAt: 4,
    },
    {
      id: 'seed-skz-sclass',
      title: 'Stray Kids — S-Class',
      subtitle: 'Сияй по-своему · S클래스',
      emoji: '💎',
      colorHex: '#00BCD4',
      difficulty: 'Начальный',
      sourceId: null,
      wordDefs: [
        { korean: '별', translation: 'звезда' },
        { korean: '빛나다', translation: 'сиять, сверкать' },
        { korean: '매력', translation: 'очарование, привлекательность' },
        { korean: '개성', translation: 'индивидуальность' },
        { korean: '자신감', translation: 'уверенность' },
        { korean: 'Style', translation: 'стиль' },
        { korean: 'S클래스', translation: 'S-класс (уровень)' },
      ],
      createdAt: 5,
    },
    ...zhSeedPacks(),
  ];
}